### SINGUP
POST {{apiUrl}}/v1/auth/signup

{
  "email": "test@liam.moc",
  "password": "Aa12345678"
}

### SIGNIN
POST {{apiUrl}}/v1/auth/signin

{
  "email": "test@liam.moc",
  "password": "Aa12345678"
}